spring.application.name=NotifyService

# Port
server.port=8085

# Cấu hình kết nối RabbitMQ Server
spring.rabbitmq.host=127.0.0.1
spring.rabbitmq.port=5672
spring.rabbitmq.username=tanvt
spring.rabbitmq.password=123@
spring.rabbitmq.virtual-host=/

