spring.application.name=ConfigServer

# Port
server.port=8763

# # Cấu hình Eureka Client
# eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# # Đăng ký với Eureka Server
# eureka.client.register-with-eureka=true

# # Lấy danh sách các service từ Eureka Server
# eureka.client.fetch-registry=true

# Khai báo đọc cấu hình trong config
spring.cloud.config.server.bootstrap=true
spring.profiles.active=native
spring.cloud.config.server.native.search-locations=classpath:/config
spring.cloud.config.fail-fast=true

