spring.application.name=APIGateway

# Port
server.port=8762

# Cấu hình Eureka Client
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Đăng ký với Eureka Server
eureka.client.register-with-eureka=true

# Lấy danh sách các service từ Eureka Server
eureka.client.fetch-registry=true

