input {
    jdbc {
        jdbc_connection_string => "jdbc:mysql://host.docker.internal:3306/testingsystem?user=root&password=root"
        #jdbc_connection_string => "jdbc:mysql://192.168.1.71:3306/microservice"(Ubuntu using ip)
        jdbc_user => "root"
        jdbc_password => "root"
        jdbc_driver_library => "/usr/share/logstash/logstash-core/lib/mysql-connector-java-8.0.26.jar"
        jdbc_driver_class => "com.mysql.cj.jdbc.Driver"
        statement => "SELECT * FROM account WHERE CreateDate >:sql_last_value ORDER BY CreateDate"
        use_column_value => true
        tracking_column => CreateDate
        tracking_column_type => "timestamp"
        schedule => "* * * * *"
    }
}
output {
    elasticsearch {
        index => "logstash-%{+YYYY.MM.dd}"
        hosts => ["http://elasticsearch:9200"]
        action=>index
        document_id => "%{accountid}"
        doc_as_upsert => true
    }
}


