spring.application.name=NotifyService

# Port
server.port=8085

spring.datasource.url=jdbc:mysql://localhost:3306/UserService?createDatabaseIfNotExist=true

# Cấu hình kết nối RabbitMQ Server
spring.rabbitmq.host=127.0.0.1
spring.rabbitmq.port=5672
spring.rabbitmq.username=tanvt
spring.rabbitmq.password=123@
spring.rabbitmq.virtual-host=/

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=thaotranyt01@gmail.com
spring.mail.password=xzkw vfcl gvio cdjp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.default-encoding=UTF-8